In [1]:
import torch 
import numpy as np


In [2]:
torch.__version__

'2.5.1+cu118'

In [6]:
arr = np.array([1,2,3,4,5,65,6,7])
print(arr)

[ 1  2  3  4  5 65  6  7]


In [9]:
arr.dtype
type(arr)

numpy.ndarray

In [10]:
x = torch.from_numpy(arr)

In [12]:
type(x)

torch.Tensor

In [13]:
torch.as_tensor(x)

tensor([ 1,  2,  3,  4,  5, 65,  6,  7], dtype=torch.int32)

In [14]:
type(x)

torch.Tensor

In [15]:
x.dtype

torch.int32

In [17]:
# 2D Array 

In [23]:
arr2d = np.arange(0.0 , 12.0)
arr2d = arr2d.reshape(4,3)


In [22]:
print(arr2d)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [24]:
y = torch.from_numpy(arr2d)

In [25]:
print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)


In [26]:
arr[0] = 99
print(arr)

[99  2  3  4  5 65  6  7]


In [27]:
x

tensor([99,  2,  3,  4,  5, 65,  6,  7], dtype=torch.int32)

In [28]:
my_arr = np.arange(0 , 10)

In [29]:
my_tensor = torch.tensor(my_arr)

In [31]:
my_other_tensor = torch.from_numpy(my_arr)

In [32]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [33]:
my_arr[0] = 999


In [34]:
my_arr

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [35]:
my_other_tensor

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [36]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [37]:
new_arr = np.array([1,2,3])
new_arr.dtype

dtype('int32')

In [39]:
my_tensor = torch.FloatTensor(new_arr)
my_tensor

tensor([1., 2., 3.])

In [40]:
my_tensor.dtype

torch.float32

In [41]:
torch.empty(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [43]:
torch.empty(2,2)

tensor([[-6.6322e+12,  1.4447e-42],
        [ 0.0000e+00,  0.0000e+00]])

In [44]:
torch.empty(5,3)

tensor([[-6.7689e+12,  1.4447e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [45]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [48]:
torch.zeros(4,1 , dtype = torch.int64)

tensor([[0],
        [0],
        [0],
        [0]])

In [49]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [51]:
torch.ones(4,2 , dtype = torch.int64)

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])

In [52]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [64]:
torch.linspace(0,18,12).reshape(4,3)

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])

In [65]:
torch.tensor([1,2,3,4,5,6])

tensor([1, 2, 3, 4, 5, 6])

In [66]:
my_tensor = torch.Tensor([1,2,3])

In [68]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [69]:
my_tensor.dtype

torch.float32

In [70]:
torch.rand(4,3)

tensor([[0.4065, 0.3833, 0.6785],
        [0.8689, 0.9633, 0.7666],
        [0.3290, 0.5645, 0.4366],
        [0.6426, 0.5776, 0.0754]])

In [73]:
torch.randn(4,3)

tensor([[ 0.9517, -1.7878,  0.1338],
        [-0.4187, -0.8952,  0.1205],
        [ 0.1982,  0.2708, -0.5450],
        [-0.4081,  1.3199,  1.1962]])

In [80]:
torch.randint(low = 0 , high = 10 , size= (3,3))

tensor([[2, 9, 0],
        [1, 9, 7],
        [5, 0, 6]])

In [83]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [84]:
x.shape

torch.Size([2, 5])

In [85]:
torch.rand_like(x)

tensor([[0.1640, 0.0989, 0.1775, 0.2301, 0.9431],
        [0.6314, 0.9159, 0.1301, 0.1612, 0.9527]])

In [86]:
# Tensor Operations 

In [88]:
alpha = torch.arange(6).reshape(3,2)

In [89]:
alpha

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [91]:
alpha[:1]

tensor([[0, 1]])

In [96]:
alpha[: , 1:]
alpha.shape


torch.Size([3, 2])

In [98]:
alpha[0] = 9999999


In [99]:
alpha

tensor([[9999999, 9999999],
        [      2,       3],
        [      4,       5]])

In [101]:
alpha.shape

torch.Size([3, 2])

In [102]:
alpha.view(2, -1)

tensor([[9999999, 9999999,       2],
        [      3,       4,       5]])

In [104]:
a = torch.tensor( [1 , 2 , 2 ])

In [105]:
a

tensor([1, 2, 2])

In [109]:
b = torch.tensor([43,5,56])

In [112]:
torch.add(a , b)

tensor([44,  7, 58])

In [111]:
a + b

tensor([44,  7, 58])

In [113]:
a.mul(b)

tensor([ 43,  10, 112])

In [114]:
a.dot(b)

tensor(165)

In [116]:
a = torch.tensor([[0,2,4] , [1,2,4]])

In [117]:
a

tensor([[0, 2, 4],
        [1, 2, 4]])

In [118]:
b = torch.tensor([[5,6,7] , [8,9,10]])

In [119]:
b

tensor([[ 5,  6,  7],
        [ 8,  9, 10]])

In [121]:
b.shape

torch.Size([2, 3])

In [123]:
a.shape

torch.Size([2, 3])

In [126]:
a & b

tensor([[0, 2, 4],
        [0, 0, 0]])

In [127]:
a + b

tensor([[ 5,  8, 11],
        [ 9, 11, 14]])

In [128]:
a | b

tensor([[ 5,  6,  7],
        [ 9, 11, 14]])

In [130]:
# Eucledian Distance

In [131]:
x = torch.tensor([1,2,3,4,5])

In [132]:
x

tensor([1, 2, 3, 4, 5])

In [133]:
x.norm

<bound method Tensor.norm of tensor([1, 2, 3, 4, 5])>

In [135]:
x.numel()

5

In [136]:
# Excercise Pytorch

In [139]:
np.random.seed(42)
torch.manual_seed(42)


In [140]:
# Create a Numy array contane 6 random integers between o and 5

In [141]:
arr = np.random.randint(0,5,6)
arr

array([3, 4, 2, 4, 4, 1])

In [142]:
arr = torch.from_numpy(arr)
arr

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [144]:
x = x.type(torch.int64)
x

tensor([1, 2, 3, 4, 5])

In [145]:
x.type

<function Tensor.type>

In [146]:
x.dtype

torch.int64

In [147]:
x.reshape

<function Tensor.reshape>

In [150]:
x

tensor([1, 2, 3, 4, 5])

In [151]:
x * x 

tensor([ 1,  4,  9, 16, 25])

In [154]:
y = torch.randint( 0 , 5 , (2,3))

In [155]:
y

tensor([[2, 2, 1],
        [4, 1, 0]])

In [162]:
#   Deep Learning CNN Overview Pytorch